- pipeline:
    name: check
    manager: independent
    trigger:
      github_conn:
        event:
          - pull_request
        action:
          - opened
          - changed
    success:
      github_conn:
        comment: true
        status: success
    failure:
      github_conn:
        comment: true
        status: failure
    merge-failure:
      github_conn:
        comment: true
        status: failure
    start:
      github_conn:
        comment: true
        status: pending
    disabled:
      github_conn:
        comment: true



- project:
    name: jluk-codi-org/zuul-test
    check:
      jobs:
        - noop
        - otherone
